"""business_foundation"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("width_mm", sa.Float(), nullable=False),
        sa.Column("depth_mm", sa.Float(), nullable=False),
        sa.Column("height_mm", sa.Float(), nullable=False),
        sa.Column("thumbnail", sa.String(length=2048), nullable=True),
        sa.Column("model_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "depth_mm > 0 AND depth_mm < 'Infinity'::float8",
            name=op.f("ck_products_depth_mm"),
        ),
        sa.CheckConstraint(
            "height_mm > 0 AND height_mm < 'Infinity'::float8",
            name=op.f("ck_products_height_mm"),
        ),
        sa.CheckConstraint(
            "price >= 0 AND price < 'Infinity'::numeric", name=op.f("ck_products_price")
        ),
        sa.CheckConstraint(
            "width_mm > 0 AND width_mm < 'Infinity'::float8",
            name=op.f("ck_products_width_mm"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_products_merchant_id_merchants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("merchant_id", "id", name=op.f("uq_products_merchant_id")),
        sa.UniqueConstraint("merchant_id", "sku", name="uq_products_merchant_sku"),
    )
    op.create_index(
        op.f("ix_products_merchant_id"), "products", ["merchant_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="sales", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('owner','sales')", name=op.f("ck_users_role")),
        sa.CheckConstraint(
            "email = lower(trim(email))", name=op.f("ck_users_email_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_users_merchant_id_merchants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("merchant_id", "email", name="uq_users_merchant_email"),
        sa.UniqueConstraint("merchant_id", "id", name=op.f("uq_users_merchant_id")),
    )
    op.create_index(
        op.f("ix_users_merchant_id"), "users", ["merchant_id"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("wechat", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("budget", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="new", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "budget >= 0 AND budget < 'Infinity'::numeric",
            name=op.f("ck_customers_budget"),
        ),
        sa.CheckConstraint(
            "status IN ('new','following','won','lost')",
            name=op.f("ck_customers_status"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "owner_user_id"],
            ["users.merchant_id", "users.id"],
            name=op.f("fk_customers_merchant_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_customers_merchant_id_merchants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("merchant_id", "id", name=op.f("uq_customers_merchant_id")),
    )
    op.create_index(
        op.f("ix_customers_merchant_id"), "customers", ["merchant_id"], unique=False
    )
    op.create_table(
        "design_projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("sales_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','active','archived')",
            name=op.f("ck_design_projects_status"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "customer_id"],
            ["customers.merchant_id", "customers.id"],
            name=op.f("fk_design_projects_merchant_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id", "sales_user_id"],
            ["users.merchant_id", "users.id"],
            name=op.f("fk_design_projects_merchant_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_design_projects_merchant_id_merchants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_projects")),
        sa.UniqueConstraint(
            "merchant_id", "id", name=op.f("uq_design_projects_merchant_id")
        ),
    )
    op.create_index(
        op.f("ix_design_projects_merchant_id"),
        "design_projects",
        ["merchant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_design_projects_merchant_id"), table_name="design_projects")
    op.drop_table("design_projects")
    op.drop_index(op.f("ix_customers_merchant_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_users_merchant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_products_merchant_id"), table_name="products")
    op.drop_table("products")
    op.drop_table("merchants")
    # ### end Alembic commands ###
